- name: Append MongoDB HAProxy block
  hosts: mongo
  become: yes
  
  vars:
    vip_address: 10.2.100.100
    network_interface: ens160
    router_id: 51
    auth_pass: 42keepalived
    priority: 100   # 노드별로 override 가능 (host_vars로 관리 가능)
    mongo_nodes:
      - name: mongo1
        ip: 10.2.100.21
      - name: mongo2
        ip: 10.2.100.22
      - name: mongo3
        ip: 10.2.100.23
  tasks:
    - name: Append MongoDB block using external template
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        marker: "# {mark} ANSIBLE MANAGED BLOCK - MONGODB"
        block: "{{ lookup('template', 'templates/mongodb.j2') }}"
        create: yes

    - name: Ensure chk_haproxy script is installed
      template:
        src: templates/chk_haproxy.sh.j2
        dest: /usr/local/bin/chk_haproxy.sh
        mode: '0755'

    - name: Deploy keepalived.conf
      template:
        src: templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        mode: '0644'

    - name: Restart keepalived
      service:
        name: keepalived
        
    - name: Reload HAProxy
      service:
        name: haproxy
        state: reloaded
