[pgnode]
db01 ansible_host=127.0.0.1 ansible_connection=local
db02 ansible_host=10.2.100.22
db03 ansible_host=10.2.100.23

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_become=true
ansible_become_method=sudo
ansible_become_password=ubuntu


