---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jenkins-admin-secret
  namespace: jenkins
spec:
  encryptedData:
    JENKINS_ADMIN_ID: AgBx0ZTPHlQApnkEiYehWnm0SFZTbri1dy5vMtbUc5YaBuVYYHo+XthYMMPIKK/OQvFhAZRjdqLfIqDiBlIgoUMBx+E2xoDjxnQlAPNXBdVDRtyoPpXfLhX2lkAHLEG5wC4pVrK5WcEPhj9lzXTqBbeufos9xhYTMNg38WJkURotw7iI5JRGuYMINNEGmzwHFENOF+j44fK0bDlhAO4wFN/fvXRrbjvr0mlq4DKEYnONkCaVAfFk7vh0kRn4YoqfDqqQ5vxdqpRA15OTrCc6GFfy5nMLnUTIYhMgDW15n5mofdz+AojwA4DJEFroM2BDfUj1Ml+Lc1LDwjVMJFAzCD6MJMNgoXTeJNO4wML0sWIL29NyMD7dqRWo/7StZEGHxknhOkohODtnagGFVEhPVoA7FZy8r+Pgkvn3392O9nWqXX4khVQVs/3N2D4fE0JlgbDiBYG1vA8onOrTtu/LlZ2F3+0ER159J/tiU3lB7SCZLV7tUJHsnM/QuUmeSuIZrn6eXiAtaz5fmO6KVV8C7S2qTjx9NhpovDDd+LDvfsGfuH+jxGssZ3mQbqb9oloIvK+uSfqsqlOsgaV6KYuHOzE1+r9d6Im+h669h+L9ejacRP6B8jVwGGOgxP++59nI5l5IZg5lY7fEEaMX6JJbQz269b/ABXmGoazLTi8Ukv3XIxPfowm0bh1hgHBUlh/BtZEsphVRHA==
    JENKINS_ADMIN_PASSWORD: AgB4Gg3QYZ0y9SaCQGbnTnRBzP0Dgd1Nt1tD+eNSNb5PK/j7c5BnTceLlvER21Equ4htz/koZ6QQ+I2FM9LmWrPqDuqyaDivnmNusHjctf2FowkMOg6yMlQdIYmWHy4keQ7URhEQJqe+t5EVdocM8fpAFGwU4a7EuNuvU1/t4UakonWlADpkc4QY8P2U58qO7kw2BhvwaorqQ5AD5BzfC5fPsmHFZt4ZZ2qt2lqc0MVYABUC4NQj1aGwK+OQcE9NgTf7RV7XTmktDV3tcbAwqWCIIsIgQmNUPWOuns9ECKjwkkw96sph//czW4j61fYYdfJXVGNrxDJD41Wg5Itgp9/yNas2zF+i7Nv3royMhXtDodS7NHd5OXwKD994gXq/1231h0VouoIvVuN8x7Dkeopx1v1yyNHBDib/dW3IxQpao+rdfYFl1UZvOURoTQ7a35Qgpd5PJDNVsiMvxSq9spg3LfgDM+4QVVxOs52MjLvXyJDQH3pw3kUakFUso7gb9S1bjxQ6nhLw/Ivx1jpRLViYU7BIMBWt/woICofTwnjkO6sGx3/lIu8jyGbEouqeUjQCRxxqmylbJsk4xF74uBth5vcIPkYwUpSdcgXOlgEeR7bRkFYiSX0HjLxKsZ+9tUZoqGXPwyubb4txEVLppciRnXBVt7WGItf33Nk0UZKGeRSlkcuaGPkg0NcEfxBNs2QkCh6OQAWRYMQ5QaHI
  template:
    metadata:
      creationTimestamp: null
      name: jenkins-admin-secret
      namespace: jenkins
    type: Opaque