config:
  service: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        Health_Check On

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off

  outputs: |
    [OUTPUT]
        Name es
        Match *
        Host 10.2.200.1
        Port 9200
        Logstash_Format Off
        Suppress_Type_Name On
        Retry_Limit False

serviceAccount:
  create: true
  name: fluent-bit
