apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "was-app.fullname" . }}
  labels:
    {{- include "was-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "was-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "was-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "was-app.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: BUCKET_NAME
              value: {{ .Values.env.BUCKET_NAME | quote }}
            - name: KAFKA_IP
              value: {{ .Values.env.KAFKA_IP | quote }}
            - name: KAFKA_CONSUMER_GROUP
              value: {{ .Values.env.KAFKA_CONSUMER_GROUP | quote }}
            - name: POSTGRESQL_URL
              value: {{ .Values.env.POSTGRESQL_URL | quote }}
            - name: REDIS_PORT
              value: {{ .Values.env.REDIS_PORT | quote }}
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: ACCESS_KEY_ID
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: SECRET_ACCESS_KEY
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: POSTGRESQL_USERNAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: POSTGRESQL_PASSWORD
            - name: SMS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: SMS_API_KEY
            - name: SMS_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: SMS_API_SECRET
            - name: SMS_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: SMS_PHONE_NUMBER
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: REDIS_HOST
            - name: FRONT_URL
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: FRONT_URL
            - name: VWORLD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: VWORLD_API_KEY
            - name: OPENAI_API
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: OPENAI_API
            - name: PERPLEXITY_API
              valueFrom:
                secretKeyRef:
                  name: was-secret
                  key: PERPLEXITY_API
            
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
