apiVersion: v1
kind: Service
metadata:
  name: {{ include "was-app.fullname" . }}
  labels:
    {{- include "was-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "was-app.selectorLabels" . | nindent 4 }}
