- name: Install PostgreSQL on Ubuntu
  hosts: pgsql
  become: yes

  tasks:
    - name: Ensure APT cache is updated
      ansible.builtin.apt:
        update_cache: yes

    - name: Install PostgreSQL
      ansible.builtin.apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present

    - name: Ensure PostgreSQL is started and enabled
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: yes

    - name: Ensure PostgreSQL is accepting connections
      ansible.builtin.lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#?listen_addresses ='
        line: "listen_addresses = '*'"
      notify: Restart PostgreSQL

    - name: Allow all connections (for testing purposes only - be careful!)
      ansible.builtin.lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: "host    all             all             0.0.0.0/0               md5"
        create: yes
        insertafter: EOF
      notify: Restart PostgreSQL

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted
                                                                                                                                            